//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.17 at 09:31:27 AM EST 
//


package com.github.markusbernhardt.xmldoclet.xjc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.markusbernhardt.xmldoclet.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.markusbernhardt.xmldoclet.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link AnnotationElement }
     * 
     */
    public AnnotationElement createAnnotationElement() {
        return new AnnotationElement();
    }

    /**
     * Create an instance of {@link AnnotationInstance }
     * 
     */
    public AnnotationInstance createAnnotationInstance() {
        return new AnnotationInstance();
    }

    /**
     * Create an instance of {@link AnnotationArgument }
     * 
     */
    public AnnotationArgument createAnnotationArgument() {
        return new AnnotationArgument();
    }

    /**
     * Create an instance of {@link Enum }
     * 
     */
    public Enum createEnum() {
        return new Enum();
    }

    /**
     * Create an instance of {@link EnumConstant }
     * 
     */
    public EnumConstant createEnumConstant() {
        return new EnumConstant();
    }

    /**
     * Create an instance of {@link Interface }
     * 
     */
    public Interface createInterface() {
        return new Interface();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link Constructor }
     * 
     */
    public Constructor createConstructor() {
        return new Constructor();
    }

    /**
     * Create an instance of {@link Method }
     * 
     */
    public Method createMethod() {
        return new Method();
    }

    /**
     * Create an instance of {@link MethodParameter }
     * 
     */
    public MethodParameter createMethodParameter() {
        return new MethodParameter();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link TypeInfo }
     * 
     */
    public TypeInfo createTypeInfo() {
        return new TypeInfo();
    }

    /**
     * Create an instance of {@link TypeParameter }
     * 
     */
    public TypeParameter createTypeParameter() {
        return new TypeParameter();
    }

    /**
     * Create an instance of {@link Wildcard }
     * 
     */
    public Wildcard createWildcard() {
        return new Wildcard();
    }

    /**
     * Create an instance of {@link TagInfo }
     * 
     */
    public TagInfo createTagInfo() {
        return new TagInfo();
    }

}
